### ISSUE TITLE
Komische branches

### ISSUE THREAD

**Issue by Xyndra** [HGLabor/subwaysurfers#11]
Die branches werden nicht erklärt und ich habe keine Ahnung, welchen ich anschauen soll. Bitte schreibe ein paar Dinge in die README Dateien, damit klarer wird, welcher branch aktuell ist, denn laut meinem Verständnis gibt es für diese Repository keinen wirklichen Grund, mehrere Branches zu haben

**Comment by copyandexecute** [comment]
das stimmt

**Comment by Xyndra** [comment]
also ich würde einen Fix recht schön finden, oder wenigstens eine Erklärung

**Comment by Xyndra** [comment]
was für completed hä
